name: 24-7 Dedicated VPS Server
on:
  workflow_dispatch:

jobs:
  vps-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Xray Core
        run: |
          sudo apt-get update
          bash <(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)
          sudo mkdir -p /usr/local/etc/xray
          sudo cat <<EOF > /usr/local/etc/xray/config.json
          {
            "inbounds": [{
              "port": 54321,
              "protocol": "vless",
              "settings": {
                "clients": [{"id": "662b662b-662b-662b-662b-662b662b662b"}],
                "decryption": "none"
              },
              "streamSettings": { "network": "ws" }
            }],
            "outbounds": [{ "protocol": "freedom" }]
          }
          EOF
          sudo systemctl start xray

      - name: Run Cloudflare Quick Tunnel
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
          sudo cloudflared tunnel --url http://localhost:54321
